<?php

use Drupal\editor\Entity\Editor;

/**
 * Implements hook_form_alter().
 */
function si8_utils_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {

  if ($form['#id'] == 'views-exposed-form-ricerca-ricerca') {
    $form['key']['#placeholder'] = t('Search');
    $form['actions']['submit']['#attributes']['class'][] = 'fa fa-search';
    $form['actions']['submit']['#value'] = '';
  }

  if ($form['#id'] == 'views-exposed-form-glossario-glossario') {
    $form['key']['#placeholder'] = t('Search');
    $form['actions']['submit']['#attributes']['class'][] = 'fa fa-search';
    $form['actions']['submit']['#value'] = '';
  }

  if ($form['#id'] == 'views-exposed-form-trova-procedimento-procedimenti') {
    $form['key']['#placeholder'] = t('Search');
    $form['actions']['submit']['#attributes']['class'][] = 'fa fa-search';
    $form['actions']['submit']['#value'] = '';
  }

  if ($form['#id'] == 'views-exposed-form-bandi-bandi') {
    $form['key']['#placeholder'] = t('Search');
    $form['actions']['submit']['#attributes']['class'][] = 'fa fa-search';
    $form['actions']['submit']['#value'] = '';
  }

  if ($form['#id'] == 'views-exposed-form-domande-frequenti-faq') {
    $form['key']['#placeholder'] = t('Search');
    $form['actions']['submit']['#attributes']['class'][] = 'fa fa-search';
    $form['actions']['submit']['#value'] = '';
  }

}

function si8_utils_ckeditor_css_alter(array &$css, Editor $editor) {
  $css[] = drupal_get_path('module', 'si8_utils') . '/css/ckeditor.css';
}
