<?php

/**
 * Implements hook_theme().
 */
function bandi_theme($existing, $type, $theme, $path) {
  return array(
    'bandipdf' => [
      'variables' => [
        'title' => NULL,
        'content' => [],
        'url' => NULL,
      ],
    ],
  );
}

function bandi_preprocess_html(&$vars) {
  
  $route_object = \Drupal::routeMatch()->getRouteObject();
 
  // Se non ci sono facet, redirect ai bandi "attivi"
  if ($route_object->getPath() == '/agevolazioni') {
    if (empty(\Drupal::request()->query->get('f')) && empty(\Drupal::request()->query->get('key'))) {
      $url = Url::fromUri('internal:/agevolazioni', ['absolute' => TRUE, 'query' => ['f[0]' => 'bandi_attivi:Attive']]);
      $response = new RedirectResponse($url->toString(), 302);
      $response->send();
      $response->send();
    }
  }
  
}