module:
  admin_toolbar: 0
  automated_cron: 0
  bandi: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor: 0
  config: 0
  config_translation: 0
  content_moderation: 0
  contextual: 0
  ctools: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  diff: 0
  dynamic_page_cache: 0
  editor: 0
  entity_reference_revisions: 0
  facets: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  help: 0
  image: 0
  language: 0
  libraries: 0
  link: 0
  locale: 0
  menu_block: 0
  menu_ui: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  rdf: 0
  search_api: 0
  search_api_pantheon: 0
  search_api_solr: 0
  shortcut: 0
  si8_utils: 0
  smart_trim: 0
  sportelli: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  toolbar_menu: 0
  twig_tweak: 0
  update: 0
  user: 0
  views_ui: 0
  workflows: 0
  menu_admin_per_menu: 1
  menu_link_content: 1
  pathauto: 1
  content_translation: 10
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
  bootstrap: 0
  si8: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
langcode: it
