module:
  admin_toolbar: 0
  automated_cron: 0
  block: 0
  block_content: 0
<<<<<<< HEAD
  block_visibility_groups: 0
  block_visibility_groups_admin: 0
=======
>>>>>>> 32eeb6dd4024621a52314f099611790612920edc
  breakpoint: 0
  ckeditor: 0
  config: 0
  config_translation: 0
  content_moderation: 0
  contextual: 0
  ctools: 0
<<<<<<< HEAD
  ctools_block: 0
  datetime: 0
  dblog: 0
  devel: 0
  devel_generate: 0
  diff: 0
  dynamic_page_cache: 0
  editor: 0
  externalauth: 0
=======
  datetime: 0
  dblog: 0
  diff: 0
  dynamic_page_cache: 0
  editor: 0
>>>>>>> 32eeb6dd4024621a52314f099611790612920edc
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  help: 0
  image: 0
  language: 0
<<<<<<< HEAD
  layout_discovery: 0
=======
>>>>>>> 32eeb6dd4024621a52314f099611790612920edc
  link: 0
  locale: 0
  menu_block: 0
  menu_ui: 0
<<<<<<< HEAD
  migrando: 0
  migrate: 0
  migrate_drupal: 0
  migrate_plus: 0
  migrate_tools: 0
  node: 0
  options: 0
  page_cache: 0
  panelizer: 0
  panelizer_quickedit: 0
  panels: 0
  panels_ipe: 0
  path: 0
  quickedit: 0
  rdf: 0
  samlauth: 0
  search_api: 0
  search_api_db: 0
  search_api_solr: 0
=======
  node: 0
  options: 0
  page_cache: 0
  path: 0
  quickedit: 0
  rdf: 0
>>>>>>> 32eeb6dd4024621a52314f099611790612920edc
  shortcut: 0
  system: 0
  taxonomy: 0
  text: 0
<<<<<<< HEAD
  toolbar: 0
=======
  token: 0
  toolbar: 0
  twig_tweak: 0
>>>>>>> 32eeb6dd4024621a52314f099611790612920edc
  update: 0
  user: 0
  views_ui: 0
  workflows: 0
  menu_link_content: 1
<<<<<<< HEAD
=======
  pathauto: 1
>>>>>>> 32eeb6dd4024621a52314f099611790612920edc
  content_translation: 10
  views: 10
  standard: 1000
theme:
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
langcode: it
