session:
  parameter: language
url:
  source: path_prefix
  prefixes:
    en: en
    it: it
    es: es
<<<<<<< HEAD
=======
    '': null
>>>>>>> 32eeb6dd4024621a52314f099611790612920edc
  domains:
    en: ''
    it: ''
    es: ''
selected_langcode: site_default
_core:
  default_config_hash: uEePITI9tV6WqzmsTb7MfPCi5yPWXSxAN1xeLcYFQbM
langcode: it
