display:
  default:
    display_options:
      exposed_form:
        options:
          exposed_sorts_label: 'Order by'
      filters:
        search_api_fulltext:
          expose:
            label: Search
